import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "@westy/shared/ui/modernist.css";
import "@westy/shared/ui/westy.css";
import { AskWestyFAB } from "@/components/AskWestyFAB";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        {children}
        <AskWestyFAB />
      </body>
    </html>
  );
}
